# Prova Parcial



**Dados:**

São dois arquivos csv:

1. dataset_alunos.csv:
    1. household_key: identificador da família
    2. WEEK_NO_BINNED: identificador do intervalo de 12 semanas (aproximadamente 1 trimestre)
    3. SALES_VALUE: total gasto pela família
    4. COUPON_DISCOUNT: total de desconto aplicado pela utilização de cupons promocionais
    5. COUPON_DISC_BOOL: variavel binária correspondente a coluna COUPON_DISCOUNT
2. hh_demog_alunos.csv: contém diversas caracterizações relacionadas a cada família

**Objetivo:**

O objetivo do exercício será montar um modelo para estimar a variável SALES_VALUE no intervalo (84, 96], ou seja da 85a até a 96a semana.

**Métrica:**

Será utilizada a métrica RMSE

**Arquivo a ser submetido (IMPORTANTE):**

Voces deverão submeter o jupyter notebook junto com o arquivo csv `dataset_alunos.csv` trocando o `"alunos"` pelo seu nome conforme se encontra registrado no aluno online (caixa baixa, retirar acentos e substituir espaços por underscore). Seu arquivo de submissão precisa estar no mesmo formato do arquivo de dados, mas com o valor de predição na <br>
Por exemplo:
> nome: João Silva<br>
> arquivo de submissão: `dataset_joao_silva.csv`

**Outros pontos importantes:**

* Exercicio individual a ser entregue até o dia 21/abril/2020 as 23:59. 
* Alguns alunos poderão ser convocados para uma arguição oral no dia 23/abril/2020, durante o horário da aula.
* A nota será proporcional ao desempenho do modelo.
* Utilizar somente os algoritmos abordados no curso. 

**Dicas:**
- funções pd.pivot() e/ou pd.pivot_table()
- dtype 'category' do pandas (pesquisar em https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html sobre variaveis com dtype category)

## imports

In [4]:
import pandas as pd
import numpy as np

## read data

In [5]:
data_url = "https://raw.githubusercontent.com/hitoshinagano/data/main/dataset_alunos.csv"
demog_url = "https://raw.githubusercontent.com/hitoshinagano/data/main/hh_demog_alunos.csv"

In [6]:
demog = pd.read_csv(demog_url)
data = pd.read_csv(data_url, dtype = {'WEEK_NO_BINNED':'category'})

In [8]:
demog

,AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,HOMEOWNER_DESC,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC,household_key
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16
...,...,...,...,...,...,...,...,...
796,35-44,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2494
797,45-54,A,75-99K,Homeowner,Unknown,3,1,2496
798,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,2497
799,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2498
800,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2499

In [ ]:
data.query("household_key == 800")